name: Client Contract Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run Specmatic stub
      run: |
        docker run -d --name specmatic-stub \
          -v "${{ github.workspace }}/specmatic.yaml:/usr/src/app/specmatic.yaml" \
          -p 9000:9000 \
          znsio/specmatic stub
        # Wait for the stub to be ready
        sleep 10

    - name: Run contract test
      run: npm run test:contract
      env:
        STUB_URL: http://localhost:9000
    
    - name: Run Specmatic Insights Github Build Reporter
      uses: znsio/specmatic-insights-build-reporter-github-action@v2.0.2
      with:
        github-token: ${{ secrets.GH_REPOSITORY_TOKEN }}
        org-id:  66e98ee05e232d36a28f7c6c
        branch-ref: ${{ github.ref }}
        branch-name: ${{ github.ref_name }}
        build-id: ${{ github.run_id }}
        repo-name: ${{ github.event.repository.name }}
        repo-id: ${{ github.repository_id }}
        repo-url: ${{ github.event.repository.html_url }} 

    - name: Stop Specmatic stub
      if: always()
      run: docker stop specmatic-stub && docker rm specmatic-stub